### ISSUE TITLE
Buscar carros cadastrados

### ISSUE THREAD

**Issue by guigabraga** [DaviAtrock/pi-back#10]
### Descrição
Criar uma rota para busca de carros cadastrados.

### Requerimentos

- Deverá consultar no banco de dados, buscando todos os carros cadastrados;
- A resposta deverá ser enviada em formato JSON com código HTTP  e com um ARRAY mostrando todos os carros cadastrados.

### Validações

- Validar o TOKEN JWT enviado pelo HEADER da requisição.

### Parâmetros
`GET /users`
`HEADER: Authorization: Bearer ${TOKEN}`

### Resposta
Em caso de sucesso:
`STATUS_CODE: 200`
`{"status": "success", "cars": [{"car_id": string, "car_name": string, "car_brand": string, "car_plate": string, "car_chassi": string, "store_id": string}]}`

Em caso de error:
`STATUS_CODE: 400`
`{"status": "error", "description": string}`

- Validação de token:
`STATUS_CODE: 401`
`{"status": "error", "description": "token não é válido"}`

**Comment by Man0Lulu** [comment]
concluida pelo merge #43

**Comment by guigabraga** [comment]
Correção do parametro para o array que traz os carros cadastrados.
Atualmente: users: []
Correção: cars: []
