### ISSUE TITLE
Cadastro de nova loja

### ISSUE THREAD

**Issue by guigabraga** [DaviAtrock/pi-back#20]
### Descrição
Criar uma rota para cadastro de novas lojas na plataforma.

### Requerimentos

- Deverá ser gerado um UUID para identificação única da loja;
- Deverá ser inserido os dados de _store_id_, _store_name_, _store_address_ e _store_cnpj_ no banco de dados;
- Os parâmetros deverão ser enviados em formato JSON;
- A resposta deverá ser enviada em formato JSON e com código HTTP.

### Validações

- Verificar se todos os parâmetros foram enviados no corpo da requisição;
- Vaidar token do usuário;
- Validar formato de CNPJ;
- Validar storeName da loja com no mínimo 3 letras;
- Validar storeAddress com no mínimo 6 caracteres.

### Parâmetros
`POST /stores`
`HEADER: Authorization: Bearer ${TOKEN}`
`{"storeName": string, "storeAddress": string, "storeCnpj": number}`

### Resposta
Em caso de sucesso:
`STATUS_CODE: 201`
`{"status": "success", "message": "loja criada com sucesso"}`

Em caso de erro:
`STATUS_CODE: 400`
`{"status": "error", "description":  string}`

- Validação de token:
`STATUS_CODE: 401`
`{"status": "error", "description": "token não é válido"}`

**Comment by DaviAtrock** [comment]
Concluída com merge #21
