### ISSUE TITLE
Buscar lojas cadastradas

### ISSUE THREAD

**Issue by guigabraga** [DaviAtrock/pi-back#24]
### Descrição
Criar uma rota para buscar rotas cadastradas

### Requerimentos

- Deverá consultar no banco de dados, buscando todas as lojas cadastrados;
- A resposta deverá ser enviada em formato JSON com código HTTP  e com um ARRAY mostrando todas as lojas cadastradas.

### Validações

- Validar o TOKEN JWT enviado pelo HEADER da requisição.

### Parâmetros
`GET /users`
`HEADER: Authorization: Bearer ${TOKEN}`

### Resposta
Em caso de sucesso:
`STATUS_CODE: 200`
`{"status": "success", "stores": [{"store_id": string, "store_name": string, "store_address": string, "store_cnpj": string}]}`

Em caso de error:
`STATUS_CODE: 400`
`{"status": "error", "description": string}`

- Validação de token:
`STATUS_CODE: 401`
`{"status": "error", "description": "token não é válido" || "token é obrigatório"}`

**Comment by DaviAtrock** [comment]
#34
