### ISSUE TITLE
Remoção de loja

### ISSUE THREAD

**Issue by guigabraga** [DaviAtrock/pi-back#25]
### Descrição
Criar rota para remoção de lojas cadastradas

### Requerimentos

- Os parâmetros deverão ser enviados pela URL (QUERY PARAMS);
- A ação deverá remover o registro de loja do banco de dados;
- A resposta deverá ser enviada em formato JSON e om código HTTP.

### Validações

- Validar o TOKEN JWT enviado pelo HEADER da requisição;
- Validar se store_id de loja que será deletado existe no banco de dados.

### Parâmetros
`DELETE /stores`
`HEADER: Authorization: Bearer ${TOKEN}`
`?storeId=${param}`

### Resposta
Em caso de sucesso:
`STATUS_CODE: 200`
`{"status": "error", "message": "loja removida com sucesso"}`

Em caso de error:
`STATUS_CODE: 400
``{"status": "error", "description": string}`

- Validação de token:
`STATUS_CODE: 401`
`{"status": "error", "description": "token não é válido || token obrigatório"}`

**Comment by DaviAtrock** [comment]
#42

**Comment by guigabraga** [comment]
Bug ao tentar remover loja.

**Comment by DaviAtrock** [comment]
Completa com o merge #69
