### ISSUE TITLE
Documentar rota de criação de lojas

### ISSUE THREAD

**Issue by guigabraga** [DaviAtrock/pi-back#32]
### Descrição
Decumentar, com exemplos via SWAGGER-UI-EXPRESS a rota HTTP POST/stores.

**Comment by DaviAtrock** [comment]
#40 
Documentação da rota de criação de lojas concluída.

**Comment by guigabraga** [comment]
Corrigir a propriedade chamada "storeAdress" no Swagger, para o nome correto "storeAddress" (com dois D).
