### ISSUE TITLE
Cadastro de nova peça

### ISSUE THREAD

**Issue by guigabraga** [DaviAtrock/pi-back#35]
### Descrição
Criar uma rota para cadastro de nova peça.

### Requerimentos

- Deverá ser gerado um UUID para identificação única da peça;
- Deverá ser inserido os dados de part_id, part_name, part_brand, part_brand e part_price, no banco de dados;
- Os parâmetros deverão ser enviados em formato JSON;
- A resposta deverá ser enviada em formato JSON e om código HTTP.

### Validações

- Verificar se todos os parâmetros foram enviados no corpo da requisição;
- Validar o TOKEN JWT enviado pelo HEADER da requisição;
- Verificar se placa e chassi já estão cadastrados.

### Parâmetros
`POST /parts`
`HEADER: Authorization: Bearer ${TOKEN}`
`{"partName": string, "partBrand": string, "partModel": string, "partPrice": string}`

### Resposta
Em caso de sucesso:
`STATUS_CODE: 201`
`{"status": "success", "message": "peça cadastrada com sucesso"}`

Em caso de error:
`STATUS_CODE: 400`
`{"status": "error", "description": string}`

- Validação de token:
`STATUS_CODE: 401`
`{"status": "error", "description": "token não é válido"}`

**Comment by gabrielbueno3** [comment]
concluida pelo merge #38

**Comment by guigabraga** [comment]
Teste realizados com sucesso!


![Image](https://github.com/DaviAtrock/pi-back/assets/99561364/2c8a2f45-0c8c-465d-a894-b4b2fa470953)
