### ISSUE TITLE
Alterar preço do carro

### ISSUE THREAD

**Issue by guigabraga** [DaviAtrock/pi-back#45]
### Descrição
Criar uma rota para altera o preço do carro.

### Requerimentos
- Os parâmetros deverão ser enviados pela URL (QUERY PARAMS);
- A ação deverá atualizar o preço do carro no banco de dados;
- A resposta deverá ser enviada em formato JSON e om código HTTP.

### Validações

- Validar o TOKEN JWT enviado pelo HEADER da requisição;
- Validar se o cadastro do carro existe pelor carId;
- Validar se o parâmetro carPrice foi enviado;

### Parâmetros
`PUT /cars`
`HEADER: Authorization: Bearer ${TOKEN}`
`?carId=${param}&carPrice=${param}`

### Resposta
Em caso de sucesso:
`STATUS_CODE: 200`
`{"status": "success", "message": "preço alterado com sucesso"}`

Em caso de error:
`STATUS_CODE: 400 ``{"status": "error", "description": string}`

- Validação de token:
`STATUS_CODE: 401`
`{"status": "error", "description": "token não é válido"}`

**Comment by Man0Lulu** [comment]
Concluída pelo merge #63

**Comment by guigabraga** [comment]
Teste realizados com sucesso!


![Image](https://github.com/DaviAtrock/pi-back/assets/99561364/ea37b620-212c-46a3-b330-fa8d55d006f0)
