### ISSUE TITLE
Atualização de endereço de loja

### ISSUE THREAD

**Issue by guigabraga** [DaviAtrock/pi-back#50]
### Descrição
Criar uma rota para alteração de endereço de loja cadastrada.

### Requerimentos
- Os parâmetros deverão ser enviados pela URL (QUERY PARAMS);
- A ação deverá susbtituir o endereço da loja no banco de dados;
- A resposta deverá ser enviada em formato JSON e om código HTTP.

### Validações

- Validar o TOKEN JWT enviado pelo HEADER da requisição;
- Validar se a loja existe pelo storeId
- Validar se o parâmetro de novo endereço foi eviado.

### Parâmetros
`PUT /stores`
`HEADER: Authorization: Bearer ${TOKEN}`
`?storeId=${param}&storeAddress=${param} `

### Resposta
Em caso de sucesso:
`STATUS_CODE: 200`
`{"status": "success", "message": "endereço alterado com sucesso"}`

Em caso de error:
`STATUS_CODE: 400 ``{"status": "error", "description": string}`

- Validação de token:
`STATUS_CODE: 401`
`{"status": "error", "description": "token não é válido"}`

**Comment by DaviAtrock** [comment]
Concluída pelo merge #59
