### ISSUE TITLE
Cadastro de novo carro

### ISSUE THREAD

**Issue by guigabraga** [DaviAtrock/pi-back#9]
### Descrição
Criar uma rota para cadastro de novo carro.

### Requerimentos

- Deverá ser gerado um UUID para identificação única do carro;
- Deverá ser inserido os dados de car_id, car_name, car_brand, car_model, car_plate, car_chassi e car_price no banco de dados;
- Os parâmetros deverão ser enviados em formato JSON;
- A resposta deverá ser enviada em formato JSON e om código HTTP.

### Validações

- Verificar se todos os parâmetros foram enviados no corpo da requisição;
- Validar o TOKEN JWT enviado pelo HEADER da requisição;
- Verificar se placa e chassi já estão cadastrados; 
- Validar se a placa (carId) possui 7 caracteres; e
- Validar se chassi tem 17 caracteres.

### Parâmetros
`POST /cars`
`HEADER: Authorization: Bearer ${TOKEN}`
`{"carName": string, "carBrand": string, "carModel": string, "carPlate": string, "carChassi": string, "carPrice": string}`

### Resposta
Em caso de sucesso:
`STATUS_CODE: 201`
`{"status": "success", "message": "carro criado com sucesso!"}`

Em caso de error:
`STATUS_CODE: 400`
`{"status": "error", "description": string}`

- Validação de token:
`STATUS_CODE: 401`
`{"status": "error", "description": "token não é válido"}`

**Comment by Man0Lulu** [comment]
Concluída com merge #39

**Comment by guigabraga** [comment]
Testes realizados com sucesso!



![Image](https://github.com/DaviAtrock/pi-back/assets/99561364/6d2a33d1-25c0-4923-abbf-26b2ebb3121d)
